[package]
name = "geyser-grpc-plugin-server"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Jito Foundation <team@jito.network>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bs58 = "0.4.0"
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
futures-util = "0.3.25"
jito-geyser-protos = { path = "../proto" }
jito-solana-geyser-plugin-interface = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.13.6-jito", package = "solana-geyser-plugin-interface", optional = true }
jito-solana-logger = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.13.6-jito", package = "solana-logger", optional = true }
jito-solana-metrics = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.13.6-jito", package = "solana-metrics", optional = true }
jito-solana-program = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.13.6-jito", package = "solana-program", optional = true }
jito-solana-sdk = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.13.6-jito", package = "solana-sdk", optional = true }
jito-solana-storage-proto = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.13.6-jito", package = "solana-storage-proto", optional = true }
jito-solana-transaction-status = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.13.6-jito", package = "solana-transaction-status", optional = true }
jito-solana-vote-program = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.13.6-jito", package = "solana-vote-program", optional = true }
log = "0.4.14"
once_cell = "1.16.0"
prost = "0.8"
prost-types = "0.8"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.67"

solana-geyser-plugin-interface = "~1.13"
solana-logger = "~1.13"
solana-metrics = "~1.13"
solana-program = "~1.13"
solana-sdk = "~1.13"
solana-storage-proto = "~1.13"
solana-transaction-status = "~1.13"
solana-vote-program = "~1.13"
thiserror = "1.0.37"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0.1"
tonic = "0.5.2"
uuid = { version = "1.2.2", features = ["v4", "fast-rng"] }

[features]
jito-solana = ["jito-solana-geyser-plugin-interface", "jito-solana-logger", "jito-solana-metrics", "jito-solana-program", "jito-solana-sdk", "jito-solana-vote-program", "jito-solana-storage-proto", "jito-solana-transaction-status"]

[build-dependencies]
tonic-build = "0.5.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
