[package]
name = "geyser-grpc-plugin-server"
version = "0.1.0"
license = "Apache-2.0"
authors = ["segfaultdoctor <seg@jito.network>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bs58 = "0.4.0"
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
log = "0.4.14"
once_cell = "1.16.0"
prost = "0.9"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.67"
solana-geyser-plugin-interface = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
solana-logger = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
solana-metrics = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
solana-program = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
solana-sdk = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
thiserror = "1.0.37"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0.1"
tonic = "0.6"
uuid = { version = "1.2.2", features = ["v4", "fast-rng"] }

[build-dependencies]
tonic-build = "0.6"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
