name: Clean Code Check
on:
  workflow_call:

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: clippy_check

      - name: Setup Rust tools
        run: cargo install cargo-sort --locked

      - name: Cargo sort
        run: cargo sort --workspace --check

      - name: Clippy Check
        run: cargo clippy --all-features --all-targets --tests
